# Generated by Django 4.2.11 on 2024-03-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_cars',
            field=models.ManyToManyField(blank=True, to='main_app.car'),
        ),
    ]
