# Generated by Django 5.0.3 on 2024-03-20 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_profile_favorite_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Wagon', 'Wagon'), ('Minivan', 'Minivan'), ('Pickup Truck', 'Pickup Truck'), ('Crossover', 'Crossover'), ('Luxury', 'Luxury'), ('Sports Car', 'Sports Car'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('Compact', 'Compact'), ('Off-road', 'Off-road'), ('Vintage', 'Vintage'), ('Exotic', 'Exotic'), ('Limousine', 'Limousine'), ('Truck', 'Truck'), ('Van', 'Van')], default='Sedan', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('Like New', 'Like New'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Damaged', 'Damaged'), ('Salvage', 'Salvage'), ('Rebuilt', 'Rebuilt'), ('Worn', 'Worn'), ('Broken', 'Broken'), ('Non-Operational', 'Non-Operational'), ('Mint Condition', 'Mint Condition'), ('Average', 'Average'), ('Scratched', 'Scratched'), ('Dented', 'Dented'), ('Rusty', 'Rusty'), ('Needs Repair', 'Needs Repair'), ('As Is', 'As Is'), ('Parts Only', 'Parts Only'), ('Scrap', 'Scrap')], default='Like New', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(choices=[('Audi', 'Audi'), ('BMW', 'BMW'), ('Cadillac', 'Cadillac'), ('Chevrolet', 'Chevrolet'), ('Ford', 'Ford'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Jeep', 'Jeep'), ('Kia', 'Kia'), ('Land Rover', 'Land Rover'), ('Lexus', 'Lexus'), ('Mazda', 'Mazda'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Nissan', 'Nissan'), ('Porsche', 'Porsche'), ('Subaru', 'Subaru'), ('Tesla', 'Tesla'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo')], default='Audi', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='milage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999, 999)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='previous_owners',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1886), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
