# Generated by Django 5.0.3 on 2024-03-20 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_car_milage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='previous_owners',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
