# Generated by Django 4.2.11 on 2024-03-21 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_car_sold'),
        ('main_app', '0011_alter_car_date_listed_alter_car_price'),
    ]

    operations = [
    ]
