# Generated by Django 4.2.11 on 2024-03-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_merge_20240320_2000'),
        ('main_app', '0012_profile_avatar_profile_bio'),
    ]

    operations = [
    ]
