# Generated by Django 4.2.11 on 2024-03-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_merge_20240320_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='sold',
            field=models.CharField(choices=[('For Sale', 'For Sale'), ('Sold', 'Sold'), ('Reserved', 'Reserved')], default='For Sale', max_length=100),
        ),
    ]
