# Generated by Django 4.2.11 on 2024-03-22 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_merge_20240321_2253'),
        ('main_app', '0013_alter_car_sold'),
    ]

    operations = [
    ]
