# Generated by Django 5.0.3 on 2024-03-21 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_car_sold'),
        ('main_app', '0014_alter_review_user_receiver_alter_review_user_sender'),
    ]

    operations = [
    ]
